### ISSUE TITLE
how to use the reference database without inputing path before it?

### ISSUE THREAD

**Issue by mingjuhao** [katholt/Kaptive#8]
Hi, thanks for your excellent work with Kaptive.
Because the reference database was downloaded seperately, I have to input the path before the database when I use the command. Can you tell me how to use the reference database without inputing path before it? If so, it will be very cool. Thanks!

**Comment by kelwyres** [comment]
Hi, 
Thanks- we are very glad that Kaptive is useful for you.
Kaptive always needs to know the precise location of your reference database, but since paths are always specified relative to the current working directory, if you launch Kaptive from the same directory that contains the database you won't need to specify the full path.
Kelly
